// THIS FILE IS AUTOGENERATED
import { _addSampleFilename as a } from "./";
declare const require: any;
require("../src/view/test_sample.tsx");
a("../src/view/test_sample.tsx");
require("../src/view/components/markdown_sample.tsx");
a("../src/view/components/markdown_sample.tsx");
require("../src/view/components/counter_sample.tsx");
a("../src/view/components/counter_sample.tsx");
require("../src/view/components/autocomplete/autocomplete_sample.tsx");
a("../src/view/components/autocomplete/autocomplete_sample.tsx");
require("../src/view/components/problem/problem_sample.tsx");
a("../src/view/components/problem/problem_sample.tsx");
require("../src/view/components/tex/index_sample.tsx");
a("../src/view/components/tex/index_sample.tsx");
require("../src/view/components/answer-input/index_sample.tsx");
a("../src/view/components/answer-input/index_sample.tsx");
