# .goreleaser.yml
# Build customization
builds:
  -
    main: backend/cmd/
    binary: cookbook
    ldflags: -s -w -X github.com/tscholl2/cookbook/backend/server.version={{.Version}}"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
